# Generated by Django 3.0.8 on 2020-07-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200721_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Quantidade'),
        ),
    ]
